# Generated by Django 5.1.7 on 2026-07-13 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="storeprofile",
            name="brand_color",
            field=models.CharField(default="#13315c", max_length=7),
        ),
        migrations.AddField(
            model_name="storeprofile",
            name="neighborhood",
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
