# Generated by Django 5.x

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_storeprofile_brand_color_storeprofile_neighborhood"),
    ]

    operations = [
        migrations.AddField(
            model_name="storeprofile",
            name="plan",
            field=models.CharField(
                choices=[("free", "Free"), ("boost", "Boost"), ("pro", "Pro")],
                default="free",
                max_length=10,
            ),
        ),
    ]
